version: "3.7"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  app:
    image: tinyurl:latest
    build:
      context: .
    environment:
      - REDIS_HOST=p
    ports:
      - 5000:5000