version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  app:
    image: lorena612/tinyurl
    build:
      context: .
    environment:
      - REDIS_HOST=redis
    ports:
      - 5000:5000